version: '1.0.{build}'
image: Visual Studio 2017
clone_depth: 1

before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: dotnet publish ./RBush/RBush.csproj -c Release

test_script:
    - cmd: cd RBush.Test
    - cmd: dotnet xunit

